### ISSUE TITLE
Criar busca e listagem da tela de Consultar Produto

### ISSUE THREAD

**Issue by victordebritto** [tarley/dispenserinove#14]
Criar funcionalidade que busca os produtos no banco de dados de acordo com o filtro.

Obs: Usar a classe de BDConnection.php para fazer o acesso ao banco de dados e utilizar métodos PDO.

**Comment by crisoares** [comment]
Estou com dificuldades para buscar a "data de validade" e o "Status do Produto" @victordebritto

**Comment by victordebritto** [comment]
Cris,
A tela de listagem de produtos não precisa de Data Validade e nem do status. Essa listagem faz parte do Crud de simples da tabela produto. Porém percebi que falta no banco de dados a coluna da Validade.
Qualquer duvida pode me mandar e-mail.

**Comment by crisoares** [comment]
Perfeito @victordebritto ,

Estou finalizando...

Ainda está dando um Warning (vide abaixo), porém acho que não está interferindo no processo.

Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\dispenserinove\Source\ConsultarProduto.php on line 49

Vou finalizar a tarefa e peço pra vc ou o @tarley  me auxiliar a resolver essa Warning.
