### ISSUE TITLE
Criação da Classe de acesso ao banco de dados

### ISSUE THREAD

**Issue by victordebritto** [tarley/dispenserinove#2]
Criar uma classe, que faça acesso ao banco de dados MySql.

**Comment by crisoares** [comment]
achei uma classe na internet...


 <?php
 /*
 Por: André Luis Alves Baltieri
 Descrição: Classe para conexão do PHP ao MySQL
 Ultima Alteração: 17/10/2007
 */
 ?>
 <?php
 //Verificação de Segurança
 $checkurl = $_SERVER["PHP_SELF"];
 if(eregi("class.MySQL.php", "$checkurl"))
 {
 header("Location: ../index.php");
 }

 class MySQL
 {
 var $host="SERVIDOR";
 var $user="USUARIO";
 var $password="SENHA";
 var $database="BASE DE DADOS";

 var $query;
 var $link;
 var $result;

 function MySQL()
 {
 //Apenas instancia o Objeto
 }

 //Esta função faz a conexão com o Banco de Dados
 function connect()
 {
 $this->link=mysql_connect($this->host,$this->user,$this->password);
 if(!$this->link)
 {
 echo "Falha na conexão com o Banco de Dados!<br />";
 echo "Erro: " . mysql_error();
 die();
 }
 elseif(!mysql_select_db($this->database, $this->link))
 {
 echo "O Bando de Dados solicitado não pode ser aberto!<br />";
 echo "Erro: " . mysql_error();
 die();
 }
 }

 //Esta função executa uma Query
 function executeQuery($query)
 {
 $this->connect();
 $this->query=$query;
 if($this->result=mysql_query($this->query))
 {
 $this->disconnect();
 return $this->result;
 }
 else
 {
 echo "Ocorreu um erro na execução da SQL";
 echo "Erro :" . mysql_error();
 echo "SQL: " . $query;
 die();
 disconnect();
 }
 }

 //Esta função desconecta do Banco
 function disconnect()
 {
 return mysql_close($this->link);
 }
 }
 ?>

**Comment by victordebritto** [comment]
Fala cris, bom dia

Essa tarefa tá no nome do carinha lá da sala, deixei ela pra ele.
Quanto a que vc fez, tá correta, porém é uma forma antiga de se conectar. Usa PDO pra acessar banco.

Qualquer coisa me chama no wpp q é mais fácil. 31-98686-7239

Enviado do Outlook Mobile<https://aka.ms/blhgte>



On Sun, May 1, 2016 at 7:06 AM -0700, "crisoares" <notifications@github.com<mailto:notifications@github.com>> wrote:


achei uma classe na internet...

<?php
/*
Por: André Luis Alves Baltieri
Descrição: Classe para conexão do PHP ao MySQL
Ultima Alteração: 17/10/2007
*/
?>
<?php
//Verificação de Segurança
$checkurl = $_SERVER["PHP_SELF"];
if(eregi("class.MySQL.php", "$checkurl"))
{
header("Location: ../index.php");
}

class MySQL
{
var $host="SERVIDOR";
var $user="USUARIO";
var $password="SENHA";
var $database="BASE DE DADOS";

var $query;
var $link;
var $result;

function MySQL()
{
//Apenas instancia o Objeto
}

//Esta função faz a conexão com o Banco de Dados
function connect()
{
$this->link=mysql_connect($this->host,$this->user,$this->password);
if(!$this->link)
{
echo "Falha na conexão com o Banco de Dados!
";
echo "Erro: " . mysql_error();
die();
}
elseif(!mysql_select_db($this->database, $this->link))
{
echo "O Bando de Dados solicitado não pode ser aberto!
";
echo "Erro: " . mysql_error();
die();
}
}

//Esta função executa uma Query
function executeQuery($query)
{
$this->connect();
$this->query=$query;
if($this->result=mysql_query($this->query))
{
$this->disconnect();
return $this->result;
}
else
{
echo "Ocorreu um erro na execução da SQL";
echo "Erro :" . mysql_error();
echo "SQL: " . $query;
die();
disconnect();
}
}

//Esta função desconecta do Banco
function disconnect()
{
return mysql_close($this->link);
}
}
?>

-

**Comment by victordebritto** [comment]
Cris essa atividade está assinada pelo FelipeRLB, pegue uma tarefa q não foi assinada.
Essa classe funciona mas usa uma forma antiga de se conectar. Procura o acesso a dados usando PDO
