### ISSUE TITLE
Disponibilizar mudanças do modelo de dados

### ISSUE THREAD

**Issue by victordebritto** [tarley/dispenserinove#3]
Disponibilizar modelo de dados com as ultimas mudanças.

**Comment by defreitaslucas** [comment]
![bd_der_dispenserinove v1 0](https://cloud.githubusercontent.com/assets/18745476/15093133/595a9bce-1454-11e6-888e-81c5769e76cc.png)

Segue a imagem do Der alterada, conforme solicitado pela turma.
O modelo criado no power design.
Script sql de criação do banco de dados.
