### ISSUE TITLE
Consultas Gerais 

### ISSUE THREAD

**Issue by pedrohanalis** [tarley/dispenserinove#34]
Pessoal acho que as consultas realizadas poderia retornar uma tela de erro ou mensagem na tela para o usuário informando que não foi localizado o mesmo,

atualmente ela apenas volta a tela com os valores zerados.

sei que não esta no escopo mais para uma nova versão seria interessante 

@victordebritto  @crisoares @Igorlgwow @dorcasmiguel

**Comment by Igorlgwow** [comment]
... sabe do que você ta precisando??
