### ISSUE TITLE
Tela Consulta Usuarios

### ISSUE THREAD

**Issue by pedrohanalis** [tarley/dispenserinove#35]
Ao efetuar a consulta de usuários ele lista de forma correta por tipo, porem na coluna do Status aparece os nomes errados,

consulta por inativo aparece o usuário inativo 
consulta por ativo aparece ativos porem mostrando na coluna como inativo 

@victordebritto  @crisoares @Igorlgwow @dorcasmiguel

**Comment by crisoares** [comment]
Fica como alteração futura,

O projeto ja foi demonstrado.
